### PR TITLE
Allow cache key customization

### PR DESCRIPTION
**Pull request by quimcastella**
Spinupwp  defines `fastcgi_cache_keys`  as `$scheme$request_method$host$request_uri`, but there are many usecases that need different the cache keys.  For example, caching specific query parameters, caching based on device category, language, etc.

This pull request introduces a new filter to allow cache key customization, while keeping the existing behavior as the default. 

For flexibility, each url is mapped to an array of cache keys, so we need to change the code to purge multiple file paths.

A real-world example is to cache 2 versions for each page: one for desktop and one for mobile. Now this can be done by changing the `fastcgi_cache_keys`  as `$scheme$request_method$host$request_uri$is_mobile` in the nginx config and then adding the following filter in functions.php.

```php
add_filter('spinupwp_cache_key_for_url', function($cache_keys, $url) {
  error_log('spinupwp_cache_key_for_url '.$cache_keys . ' '. $url);
  $parsed_url = parse_url( trailingslashit( $url ) );
  return array(
    $parsed_url['scheme'] . 'GET' . $parsed_url['host'] . $parsed_url['path'] . 'desktop',
    $parsed_url['scheme'] . 'GET' . $parsed_url['host'] . $parsed_url['path'] . 'mobile'
  );
  
}, 10, 2);
```

I've tested this usecase in our site. A common benefit is to solve [comulative layout shifts (CLS)](https://web.dev/cls/) issues.

First time opening a pull request, so please let me know if you are open to this changes and if there are any issues/style changes that I might need to solve.

### CODE REVIEW

**Comment by leeshadle** [comment]
Thank you for submitting this pull request @quimcastella!

I'm working on testing your PR and I'd like to replicate your results. I had a couple questions:
- Could you share your nginx configuration?
- How were you able to trigger the error.log from the filter you added in functions.php?

**Comment by quimcastella** [comment]
hey @leeshadle! Thanks for taking a look! 

This is the gist with the nginx config that I'm using. https://gist.github.com/quimcastella/bda709e269a2f4708938dc18b50eb52e 

The important part is:
1. Declare `map $http_user_agent $mobile_request` in `nginx.conf`
2. Use it in `/etc/nginx/sites-available/{site}/server/fastcgi-cache.conf` by appending it in the `fastcgi_cache_key "$scheme$request_method$host$request_uri$mobile_request";` 

The error log should be removed. I was just using it for debugging purposes and I left it in the example by mistake. (There is no reason to log an error there). It should look like:

``` 
add_filter('spinupwp_cache_key_for_url', function($cache_keys, $url) {
  $parsed_url = parse_url( trailingslashit( $url ) );
  return array(
    $parsed_url['scheme'] . 'GET' . $parsed_url['host'] . $parsed_url['path'] . 'desktop',
    $parsed_url['scheme'] . 'GET' . $parsed_url['host'] . $parsed_url['path'] . 'mobile'
  );
  
}, 10, 2);
```

Let me know if I can help with any other pointers.

**Comment by leeshadle** [comment]
Thank you for this @quimcastella, this is super helpful!

I'm going to give this a test and I'll let you know what I find.  I figured the error.log was for debugging/testing, so no worries there!

**Comment by leeshadle** [comment]
Hi @quimcastella!
I've done the following:
- removed the existing key in /etc/nginx/sites-available/{site}/server/fastcgi-cache.conf and replaced it with the code below:
```
#/etc/nginx/sites-available/{site}/server/fastcgi-cache.conf
# The key to use when saving cache files, which will run through the MD5 hashing algorithm.
# Custom modification to append #mobile_request defined in nginx.conf
fastcgi_cache_key "$scheme$request_method$host$request_uri$mobile_request";
```
- added the code below to the http {} section in /etc/nginx/nginx.conf
```
# Custom detection mobile vs desktop http user agent
# This is used to split the fastcgi cache key
#
# Reference
# https://stackoverflow.com/questions/62358494/how-to-config-nginx-serves-desktop-version-and-mobile-version-from-two-different
# http://detectmobilebrowsers.com/
map $http_user_agent $mobile_request {
            "~*(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino"  mobile;
            "~*^(1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-)"  mobile;
            default  desktop;
}
```
- added the code below to functions.php
```
add_filter('spinupwp_cache_key_for_url', function($cache_keys, $url) {
  error_log('spinupwp_cache_key_for_url '.$cache_keys . ' '. $url);
  $parsed_url = parse_url( trailingslashit( $url ) );
  return array(
    $parsed_url['scheme'] . 'GET' . $parsed_url['host'] . $parsed_url['path'] . 'desktop',
    $parsed_url['scheme'] . 'GET' . $parsed_url['host'] . $parsed_url['path'] . 'mobile'
  );
  
}, 10, 2);
```
- restarted nginx
- rebooted the server for good measure
- went to the frontend homepage and hello world blog post [here](https://spinupwp-plugin.webbbsite.com/) while logged in on desktop
- went to the frontend homepage and hello world blog post [here](https://spinupwp-plugin.webbbsite.com/) while logged out on desktop
- went to the frontend homepage and hello world blog post [here](https://spinupwp-plugin.webbbsite.com/) while logged out on mobile
- checked the error.log and debug.log to verify cache keys
- purged the cache for each url
- checked the error.log and debug.log to verify cache keys

- This is what I'm seeing:
Screen Shot 2023-10-13 at 2 18 53 PM
Screen Shot 2023-10-13 at 2 18 23 PM



I'm guessing I'm doing something wrong, or missing a step, that's preventing the cached keys from getting logged.  Do you have any recommendations on how I could get the cache keys to show up in the logs?

**Comment by A5hleyRich** [comment]
@leeshadle there's a typo in the filter name above, which is why you're not seeing the log entries. It should be `spinupwp_cache_keys_for_url` not `spinupwp_cache_key_for_url`.

**Comment by quimcastella** [comment]
Thanks, @A5hleyRich. Good catch!

**Comment by leeshadle** [comment]
Thank you @A5hleyRich! 🙏

**Comment by leeshadle** [comment]
Sorry @quimcastella, I've updated the filter typo, but I'm still having trouble logging the keys to verify the update is working as expected.

I'm going to try a few more things, but I was wondering if there were any other insights you could offer as to how you were able verify the cache keys were being created via the error_log?  Specifically, I'm curious what actions you had to take to get the cache_keys to populate?

**Comment by quimcastella** [comment]
hey @leeshadle! I took a moment to refresh my memory. These are the steps I took:

Set up NGINX and FASTCGI to split cache by desktop and mobile:
1. Modify etc/nginx.conf include ` map $http_user_agent $mobile_request`
2. Verify syntax: sudo nginx -t
3. Modify  |#/etc/nginx/sites-available/{site}/server/fastcgi-cache.conf| to modify key → `fastcgi_cache_key "$scheme$request_method$host$request_uri$mobile_request";`
4. Reload: `sudo systemctl reload nginx`
5. Check status: `sudo systemctl status nginx` 
6. Make sure site loads
7. Clear all caches from admin page
8. Test  cache works by loading site in icognito with different User Agents (mobile and desktop) and inspecting the page response headers (Fastcgi-Cache: HIT/MISS). You can change User Agent from the Chrome Emulated devices in Dev Tools. Make sure to have desktop and mobile user agent. 
9. After clearing the cache, you would expect a MISS then HIT for each mobile/desktop. 

The steps above are to split the cache and don't require the PR. All should work fine because when we clear the cache we delete all files without looking at the key.

The issue that this PR fixes happens we want to purge a single url with `spinupwp_purge_url( $url )`. For that we need to make the cache key in the spinupwp plugin match the cache key defined in fastcgi-cache.conf.

1. Download the PR with the new code in `src/Cache.php`
2. Add the filter in your functions.php `add_filter('spinupwp_cache_key_for_url', ...`
3. Call `spinupwp_purge_url( "https://spinupwp-plugin.webbbsite.com/" )` from somewhere. In my case, I have from a cron job, but you can also add it in functions.php for something quick. 

Note that spinupwp_purge_url is not the same as "Purge Page Cache" from the AdminBar. That deletes all pages, not only one, so it doesn't trigger the filter. This was a bit confusing to me.

Hope this helps!

**Comment by leeshadle** [comment]
Thank you for putting all of this together @quimcastella! I'll give this a go and let you know how it turns out.

**Comment by quimcastella** [comment]
I'd love to close the PR, since it has been open for a while now. @leeshadle , any chance you could take another look and finish the review?

**Comment by leeshadle** [comment]
Hi @quimcastella! I'm still reviewing the PR, but this👇 was the missing piece of the puzzle I needed, thank you! 🙏  As soon as I'm done reviewing I'll let you know.

> Call spinupwp_purge_url( "https://spinupwp-plugin.webbbsite.com/" ) from somewhere. In my case, I have a cron job, but you can call it from functions.php for something quick.

**Comment by Jamesclark32** [comment]
This is working great!

Thank you for the submission @quimcastella and the testing @leeshadle.

**Comment by quimcastella** [comment]
Awesome, thanks guys!

**Pull request merged**
